<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;</TargetFrameworks>
		<PackageIconUrl></PackageIconUrl>
		<PackageProjectUrl>https://github.com/fulviocanducci/Canducci.Excel</PackageProjectUrl>
		<RepositoryUrl>https://github.com/fulviocanducci/Canducci.Excel</RepositoryUrl>
		<RepositoryType>https://github.com/fulviocanducci/Canducci.Excel</RepositoryType>
		<Version>1.3.0.0</Version>
		<AssemblyVersion>1.3.0.0</AssemblyVersion>
		<FileVersion>1.3.0.0</FileVersion>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageTags>Excel Spreadsheet ClosedXML https://github.com/ClosedXML/ClosedXML </PackageTags>
		<PackageReleaseNotes>Update ClosedXML 0.105.0</PackageReleaseNotes>
		<Description>Canducci Excel Extensions Methods IQueryable and IEnumerable</Description>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageIcon>732220.png</PackageIcon>
		<Authors>Canducci</Authors>
		<CheckEolTargetFramework>false</CheckEolTargetFramework>
		<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\images\732220.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\README.md">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>